projname: "aDNA_assembly"
sampletsv: "test/samples.tsv"
wildcard_constraint_samples: "[A-Z]+[0-9]+"
tmpdir: "tmp"
resultdir: "results"
resourcedir: "resources"
# Assembly
assembler: "megahit"  # megahit or metaspades
readcorrection: false
min_contiglength: 500
assembly_mem: 500  # memory requested for assembly
metaspades_kmers: 21,33,55
metaspades_extra: ""
# Alignment
bowtie2_seed_nmismatches: 1
# aDNA damage analysis
pydamage: true  # perform aDNA damage analysis
# Contig annotation with Prokka
contig_annotation: true
# MAG binning
magbinning: true
magbinning_type: "individual"  # metawrap as a wrapper or individual
metabat2: true
maxbin2: true
concoct: true
min_binninglength: 1000
maxbin2_markerset: 40  # 107 (bact) or 40 (bact and arch)
# MAG refinement
magrefinement: true
magrefiner: "metawrap"  # metawrap or dastool
min_completeness: 50
max_contamination: 10
# Quality evaluation
quality_evaluation: ['checkm', 'busco', 'gunc']
reference_database: ""  # path to FastA file with reference sequences
# Taxonomic profiling
taxonomic_profiling: true
taxprofilers: ['phylophlan3', 'gtdbtk', 'kraken2']
