sampletsv: "test/samples.tsv"
tmpdir: "tmp"
resultdir: "results"
assembler: "megahit"  # megahit or metaspades
readcorrection: false
min_contiglength: 500
assembly_mem: 500  # memory requested for assembly
metaspades_kmers: 21,33,55
bowtie2_seed_nmismatches: 1
pydamage: true
